### ISSUE TITLE
Incompatible with Vue 2.6.8+

### ISSUE THREAD

**Issue by paul-muckypuddle** [jfeid/nova-google-maps#3]
The Google Maps Vue component that I presume this component relies on is broken with Vue 2.6.8 or greater. As Nova relies on Vue version ^2.0.0, this means the component no longer works when Nova's vendor code is updated and shows the error explained at https://github.com/xkjyeah/vue-google-maps/issues/592.

**Comment by paul-muckypuddle** [comment]
As per the Nova docs, on updating you need to run php artisan nova:publish, which is where Vue 2.6.10 (at the moment) breaks things. See https://nova.laravel.com/docs/2.0/installation.html#updating-nova

**Comment by jfeid** [comment]
Yes, it is a known issue. As seen by another user earlier in #2, make sure you stay with the following requirements for now:

    Laravel 5.6 or 5.7
    Nova 1.x
    Vue.js 2.5.x

I will update readme  to reflect the version requirements.

Thanks for posting.

**Comment by paul-muckypuddle** [comment]
No worries, it was actually one of my colleagues that posted the original
post. Unfortunately the project is Laravel 5.8 so downgrading isn't
particularly easy - if you're able to put the full source up I can upgrade
/ test and perhaps help bring it up to Nova 2?



[image: Copy of MP-Logo.png]

Paul Holmes

TECHNICAL DIRECTOR



0141 847 0095

paul@muckypuddle.com




WEB <https://www.muckypuddle.com/web-design>  |  APP
<https://www.muckypuddle.com/app-development>  |  BRAND
<https://www.muckypuddle.com/brand>  |  MARKETING
<https://www.muckypuddle.com/digital-marketing>

**Comment by jfeid** [comment]
If you 're in a hurry, definitely you can clone/patch/PR the source code of this package! I would be grateful if you do so. Otherwise I can upgrade it at a later time when I come back to work.

**Comment by paul-muckypuddle** [comment]
Cool will take a look!



[image: Copy of MP-Logo.png]

Paul Holmes

TECHNICAL DIRECTOR



0141 847 0095

paul@muckypuddle.com




WEB <https://www.muckypuddle.com/web-design>  |  APP
<https://www.muckypuddle.com/app-development>  |  BRAND
<https://www.muckypuddle.com/brand>  |  MARKETING
<https://www.muckypuddle.com/digital-marketing>

**Comment by jfeid** [comment]
Fixed at [v1.1](https://github.com/jfeid/nova-google-maps/releases/tag/v1.1)
